## The logic is fairly similar to the Analyst and Planner agents
import json
from ollama import chat

## System prompt for the Developer Agent
## Describe its role, the expected output format, and the rules it must follow when generating navigation code.
## These are fairly similar to the Planner Agent, but with a focus on generating code based on the plan provided by the Planner Agent.
system_prompt = """
You are a developer agent for a mobile robot.
Read the navigation plan in JSON format.
Generate Python-like pseudocode as a JSON object.
Output ONLY the JSON object. Do not write anything else.

The JSON must have exactly these keys:
"function_name": a string. The name of the function.
"steps": a list of strings. Each string is one line of pseudocode.
"actions_used": a list of actions used in the steps. Only FORWARD, LEFT, RIGHT, STOP are allowed.

Example of correct output:
{
  "function_name": "navigate",
  "steps": [
    "if path ahead is not blocked: return FORWARD",
    "if path left is not blocked: return LEFT",
    "if path right is not blocked: return RIGHT",
    "return STOP"
  ],
  "actions_used": ["FORWARD", "LEFT", "RIGHT", "STOP"]
}
"""


## Function to validate the code generated by the Developer Agent
## It should first check that the parameter it receives is of the correct type.
# Then, it should validate all the keys and values contained in the above Python data structure of the input parameter.
def validate_code(data):
    if not isinstance(data, dict):
        return False

    if "function_name" not in data:
        return False
    if "steps" not in data:
        return False
    if "actions_used" not in data:
        return False

    if not isinstance(data["function_name"], str):
        return False
    if not isinstance(data["steps"], list):
        return False
    if not isinstance(data["actions_used"], list):
        return False

    for action in data["actions_used"]:
        if action not in ["FORWARD", "LEFT", "RIGHT", "STOP"]:
            return False

    return True


## Function to run the Developer Agent
## It takes the plan generated by the Planner Agent as input, sends it to the Developer Agent. Just like you did with the Planner Agent.
## Take the response from the Developer Agent (Qwen), parse it and validate it using the validate_code function, and return the validated code.
def run_developer(plan):
    plan_text = json.dumps(plan)

    response = chat(
        model="qwen3:8b",
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": plan_text}
        ]
    )

    json_text = response.message.content
    code = json.loads(json_text)

    if validate_code(code):
        return code
    else:
        return None