## The logic is fairly similar to the Analyst and Planner agents
import json
from ollama import chat

## System prompt for the Developer Agent
## Describe its role, the expected output format, and the rules it must follow when generating navigation code.
## These are fairly similar to the Planner Agent, but with a focus on generating code based on the plan provided by the Planner Agent.
system_prompt = """
You are a developer agent for a mobile robot.
Read the navigation plan in JSON format.
Generate Python code for a function called decide_next_move(state).
Output ONLY the Python code. Do not write anything else.

The state parameter is a dictionary with these keys:
"goal_ahead": True or False
"goal_on_left": True or False
"goal_on_right": True or False
"front_blocked": True or False
"left_blocked": True or False
"right_blocked": True or False

The function must return exactly one of: "FORWARD", "LEFT", "RIGHT", "STOP".

Example of correct output:
def decide_next_move(state):
    if state["goal_ahead"] and not state["front_blocked"]:
        return "FORWARD"
    if state["goal_on_left"] and not state["left_blocked"]:
        return "LEFT"
    if state["goal_on_right"] and not state["right_blocked"]:
        return "RIGHT"
    return "STOP"
"""


## Function to validate the code generated by the Developer Agent
## It should first check that the parameter it receives is of the correct type.
# Then, it should validate all the keys and values contained in the above Python data structure of the input parameter.
def validate_code(code):
    if not isinstance(code, str):
        return False

    if "def decide_next_move(state):" not in code:
        return False

    return True


## Function to run the Developer Agent
## It takes the plan generated by the Planner Agent as input, sends it to the Developer Agent. Just like you did with the Planner Agent.
## Take the response from the Developer Agent (Qwen), parse it and validate it using the validate_code function, and return the validated code.
def run_developer(plan):
    plan_text = json.dumps(plan)

    response = chat(
        model="qwen3:8b",
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": plan_text}
        ]
    )

    code = response.message.content

    if validate_code(code):
        return code
    else:
        return None