## The logic is fairly similar to the Analyst and Planner agents
import json
from ollama import chat

## System prompt for the Planner Agent
## Describe its role, the expected output format, and the rules it must follow when generating a navigation plan.
## These are fairly similar to the Analyst Agent, but with a focus on creating a plan based on the requirements provided by the Analyst Agent.
system_prompt = """
You are a navigation planner for a mobile robot.
Read the software requirements in JSON format.
Generate a navigation plan as a JSON object.
Output ONLY the JSON object. Do not write anything else.

The JSON must have exactly these keys:
"priority": a list of actions in order of preference. Only FORWARD, LEFT, RIGHT, STOP are allowed.
"fallback": a single action to take when no priority action can be done. Only FORWARD, LEFT, RIGHT, STOP are allowed.

Example of correct output:
{
  "priority": ["FORWARD", "LEFT", "RIGHT"],
  "fallback": "STOP"
}
"""


## Function to validate the plan generated by the Planner Agent
## It should first check that the parameter it receives is of the correct type. 
# Then, it should validate all the keys and values contained in the above Python data structure of the input parameter.
def validate_plan(data):
    if not isinstance(data, dict):
        return False

    if "priority" not in data:
        return False
    if "fallback" not in data:
        return False

    if not isinstance(data["priority"], list):
        return False
    if not isinstance(data["fallback"], str):
        return False

    for action in data["priority"]:
        if action not in ["FORWARD", "LEFT", "RIGHT", "STOP"]:
            return False

    if data["fallback"] not in ["FORWARD", "LEFT", "RIGHT", "STOP"]:
        return False

    return True


## Function to run the Planner Agent
## It takes the requirements generated by the Analyst Agent as input, sends them to the Planner Agent. Just like you did with the Analyst Agent.
## Take the response from the Planner Agent (Qwen), parse it and validate it using the validate_plan function, and return the validated plan.
def run_planner(requirement):
    requirement_text = json.dumps(requirement)

    response = chat(
        model="qwen3:8b",
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": requirement_text}
        ]
    )

    json_text = response.message.content
    plan = json.loads(json_text)

    if validate_plan(plan):
        return plan
    else:
        return None